let questionsQuiz1 = [
    {
        "question": 'Wer hat HTML erfunden?',
        "answer_1": 'Robbie Williams',
        "answer_2": 'Tim Berners - Lee',
        "answer_3": 'Lady Gaga',
        "answer_4": 'Justin Bieber',
        "right_answer": '2',
        "selected_answer": '',
    },
    {
        "question": 'Was bedeutet das HTML Tag &lt;a&gt;?',
        "answer_1": 'Text Fett',
        "answer_2": 'Container',
        "answer_3": 'Ein Link',
        "answer_4": 'Kursiv',
        "right_answer": '3',
        "selected_answer": '',
    },
    {
        "question": 'Wie bindet man eine Website in eine Website ein?',
        "answer_1": '&lt;iframe&gt;, &lt;frame&gt; and &lt;frameset&gt;',
        "answer_2": '&lt;iframe&gt;',
        "answer_3": '&lt;frame&gt;',
        "answer_4": '&lt;frameset&gt;',
        "right_answer": '2',
        "selected_answer": '',
    },
    {
        "question": 'Wie stellt man Text am besten Fett dar?',
        "answer_1": '&lt;strong&gt;',
        "answer_2": 'CSS nutzen',
        "answer_3": '&lt;bold&gt;',
        "answer_4": '&lt;b&gt;',
        "right_answer": '1',
        "selected_answer": '',
    },
];

let questionsQuiz2 = [
    {
        "question": 'Wie hieß der Liedsänger von Queen?',
        "answer_1": 'Brian May',
        "answer_2": 'Roger Taylor',
        "answer_3": 'Freddie Mercury',
        "answer_4": 'John Deacon',
        "right_answer": '3',
        "selected_answer": '',
    },
    {
        "question": 'In welcher deutschen Band singt Campino?',
        "answer_1": 'Die Toten Hosen',
        "answer_2": 'Die Ärzte',
        "answer_3": 'Rammstein',
        "answer_4": 'Sportfreunde Stiller',
        "right_answer": '1',
        "selected_answer": '',
    },
    {
        "question": 'Aus wie vielen verschiedenen Noten besteht eine Dur-Tonleiter?',
        "answer_1": '6',
        "answer_2": '7',
        "answer_3": '8',
        "answer_4": '9',
        "right_answer": '3',
        "selected_answer": '',
    },
];

let questionsQuiz3 = [
    {
        "question": 'Wie heißt die Hauptstadt von Burkina Faso?',
        "answer_1": 'Honolulu',
        "answer_2": 'Sydney',
        "answer_3": 'Burkina',
        "answer_4": 'Ouagadougou',
        "right_answer": '4',
        "selected_answer": '',
    },
    {
        "question": 'Welches Land ist flächenmäßig das zweitgrößte der Erde?',
        "answer_1": 'Kanada',
        "answer_2": 'Australien',
        "answer_3": 'Russland',
        "answer_4": 'USA',
        "right_answer": '1',
        "selected_answer": '',
    },
    {
        "question": 'Welches ist das einzige deutsche Bundesland, in dem keine kreisfreie Stadt existiert?',
        "answer_1": 'Mecklenburg-Vorpommern',
        "answer_2": 'Berlin',
        "answer_3": 'Saarland',
        "answer_4": 'Hessen',
        "right_answer": '3',
        "selected_answer": '',
    },
    {
        "question": 'Welcher ist der längste Fluss der Welt?',
        "answer_1": 'Jangtsekiang',
        "answer_2": 'Mississippi',
        "answer_3": 'Amazonas',
        "answer_4": 'Nil',
        "right_answer": '4',
        "selected_answer": '',
    },
];

let questionsQuiz4 = [
    {
        "question": 'Welches Amt hat Olaf Scholz?',
        "answer_1": 'Bundesminister für Wirtschaft und Klimaschutz',
        "answer_2": 'Bundeskanzler',
        "answer_3": 'Bundesminister der Finanzen',
        "answer_4": 'Bundesminister der Justiz',
        "right_answer": '2',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Robert Habeck?',
        "answer_1": 'Bundesminister für Wirtschaft und Klimaschutz',
        "answer_2": 'Bundeskanzler',
        "answer_3": 'Bundesminister der Finanzen',
        "answer_4": 'Bundesminister der Justiz',
        "right_answer": '1',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Christian Lindner?',
        "answer_1": 'Bundesminister für Wirtschaft und Klimaschutz',
        "answer_2": 'Bundeskanzler',
        "answer_3": 'Bundesminister der Finanzen',
        "answer_4": 'Bundesminister der Justiz',
        "right_answer": '3',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Nancy Faeser?',
        "answer_1": 'Bundesministerin für Wirtschaft und Klimaschutz',
        "answer_2": 'Bundesministerin des Auswärtigen Amtes',
        "answer_3": 'Bundesministerin des Inneren und der Heimat',
        "answer_4": 'Bundesminister für Familie, Senioren, Frauen und Jugend',
        "right_answer": '3',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Annalena Baerbock?',
        "answer_1": 'Bundesministerin für Wirtschaft und Klimaschutz',
        "answer_2": 'Bundesministerin des Auswärtigen Amtes',
        "answer_3": 'Bundesministerin des Inneren und der Heimat',
        "answer_4": 'Bundesminister für Familie, Senioren, Frauen und Jugend',
        "right_answer": '2',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Marco Buschmann?',
        "answer_1": 'Bundesminister für Wirtschaft und Klimaschutz',
        "answer_2": 'Bundesminister der Verteidigung',
        "answer_3": 'Bundesminister der Finanzen',
        "answer_4": 'Bundesminister der Justiz',
        "right_answer": '4',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Hubertus Heil?',
        "answer_1": 'Bundesminister für Wirtschaft und Klimaschutz',
        "answer_2": 'Bundesminister der Verteidigung',
        "answer_3": 'Bundesminister für Arbeit und Soziales',
        "answer_4": 'Bundesminister für Gesundheit',
        "right_answer": '3',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Boris Pistorius?',
        "answer_1": 'Bundesminister für Ernährung und Landwirtschaft',
        "answer_2": 'Bundesminister der Verteidigung',
        "answer_3": 'Bundesminister für Arbeit und Soziales',
        "answer_4": 'Bundesminister für Gesundheit',
        "right_answer": '2',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Cem Özdemir?',
        "answer_1": 'Bundesminister für Ernährung und Landwirtschaft',
        "answer_2": 'Bundesminister der Verteidigung',
        "answer_3": 'Bundesminister für Arbeit und Soziales',
        "answer_4": 'Bundesminister für Gesundheit',
        "right_answer": '1',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Lisa Paus?',
        "answer_1": 'Bundesministerin für Wirtschaft und Klimaschutz',
        "answer_2": 'Bundesministerin des Auswärtigen Amtes',
        "answer_3": 'Bundesministerin des Inneren und der Heimat',
        "answer_4": 'Bundesminister für Familie, Senioren, Frauen und Jugend',
        "right_answer": '4',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Karl Lauterbach?',
        "answer_1": 'Bundeskanzler',
        "answer_2": 'Bundesminister der Verteidigung',
        "answer_3": 'Bundesminister für Arbeit und Soziales',
        "answer_4": 'Bundesminister für Gesundheit',
        "right_answer": '4',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Volker Wissing?',
        "answer_1": 'Bundesminister für besondere Aufgaben / Chef des Bundeskanzleramtes',
        "answer_2": 'Bundesminister für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz',
        "answer_3": 'Bundesminister für Bildung und Forschung',
        "answer_4": 'Bundesminister für Digitales und Verkehr',
        "right_answer": '4',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Steffi Lemke?',
        "answer_1": 'Bundesministerin für besondere Aufgaben / Chefin des Bundeskanzleramtes',
        "answer_2": 'Bundesministerin für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz',
        "answer_3": 'Bundesministerin für Bildung und Forschung',
        "answer_4": 'Bundesministerin für Digitales und Verkehr',
        "right_answer": '2',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Bettina Stark-Watzinger?',
        "answer_1": 'Bundesministerin für besondere Aufgaben / Chefin des Bundeskanzleramtes',
        "answer_2": 'Bundesministerin für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz',
        "answer_3": 'Bundesministerin für Bildung und Forschung',
        "answer_4": 'Bundesministerin für Digitales und Verkehr',
        "right_answer": '3',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Svenja Schulze?',
        "answer_1": 'Bundesministerin für wirtschaftliche Zusammenarbeit und Entwicklung',
        "answer_2": 'Bundesministerin für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz',
        "answer_3": 'Bundesministerin für Wohnen, Stadtentwicklung und Bauwesen',
        "answer_4": 'Bundesministerin für Digitales und Verkehr',
        "right_answer": '1',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Klara Geywitz?',
        "answer_1": 'Bundesministerin für wirtschaftliche Zusammenarbeit und Entwicklung',
        "answer_2": 'Bundesministerin für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz',
        "answer_3": 'Bundesministerin für Wohnen, Stadtentwicklung und Bauwesen',
        "answer_4": 'Bundesministerin für Digitales und Verkehr',
        "right_answer": '3',
        "selected_answer": '',
    },
    {
        "question": 'Welches Amt hat Wolfgang Schmidt?',
        "answer_1": 'Bundesminister für besondere Aufgaben / Chef des Bundeskanzleramtes',
        "answer_2": 'Bundesminister für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz',
        "answer_3": 'Bundesminister für Bildung und Forschung',
        "answer_4": 'Bundesminister für Digitales und Verkehr',
        "right_answer": '1',
        "selected_answer": '',
    },
];